server:
  port: 8098

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/jwt-security
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true

logging.level:
  org.hibernate.SQL: debug

sp:
  jwt:
    secret: test-secret
    token-life-time: 300
    token-refresh-time: 86400